# Site settings
title: Frey Today
header-img: 'img/home-bg.jpg'
email: hey+freytoday@frey.today
author: Frey
description: > # this means to ignore newlines until "baseurl:"
  Debugging life since 1991.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://frey.su" # the base hostname & protocol for your site
twitter_username: itsok2befrey
github_username:  Freika
paginate: 10
permalink: /:title/

# Build settings
# markdown: redcarpet
# highlighter: pygments
gems: [jekyll-paginate]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
